### ISSUE TITLE
Demo page would be good

### ISSUE THREAD

**Issue by adavie1** [BKWLD/vue-visual#14]
Maybe creating a demo page for the different properties would be a good move. After all, a picture is worth 1,000 words!

Great component though. Thanks for taking the trouble to create and share it.

**Comment by pmochine** [comment]
I'm like why is this not priority? Why should I take my time to install and see that the plugin won't work for my project...

**Comment by weotch** [comment]
This is available now at https://bkwld.github.io/vue-visual/

**Comment by pmochine** [comment]
@weotch awesome! got my star 🌟
