### ISSUE TITLE
Add support for `playsinline` attribute

### ISSUE THREAD

**Issue by thelucre** [BKWLD/vue-visual#16]
Info: https://webkit.org/blog/6784/new-video-policies-for-ios/

Either explicitly support the `playsinline` attribute as a prop or future proof by setting an attribute object as a config with boolean values, like `:attributes="{ playsinline: true, loop: false }"`

**Comment by weotch** [comment]
Oh wow, interesting!

**Comment by thelucre** [comment]
Yeah! Also, this polyfill might be useful as well: https://github.com/bfred-it/iphone-inline-video

**Comment by weotch** [comment]
I think I am gonna use that polyfill, looks pretty legit.

**Comment by weotch** [comment]
I'm going to apply `playsinline` by default, that's in the spirit of what vue-visual is for.  Note, I found in Android you'll also need to explicitly set `muted`.  IOS doesn't seem to require that.

**Comment by thelucre** [comment]
Great! I've seen desktop and mobile Safari throw an error when `muted` is missing, as well.

**Comment by weotch** [comment]
Hmmm, that polyfill wasn't working for me via browserstack.  Just gonna implement the native `playsinline` attribute.  I think that's fine...

![statcounter-ios_version-us-monthly-201704-201804](https://user-images.githubusercontent.com/77567/40752323-d983ebfe-6423-11e8-8266-46561ef509d4.png)

**Comment by weotch** [comment]
Ok, released as 0.5.0, lemme know how that goes!
