### ISSUE TITLE
Add max-width:100% to .vv-slot to prevent line wrapping when .vv-slot contents

### ISSUE THREAD

**Issue by jonjahr** [BKWLD/vue-visual#30]
https://github.com/BKWLD/vue-visual/blob/09f3f8b27f837b511b61fa69457af030e5aea071/index.vue#L149

When contents of `.vv-slot` are wider than viewport, `.vv-slot` wraps below `.vv-aspect-shim`.  Recommend adding `max-width:100%` to `.vv-slot`.  I know the consumer can solve this by styling their own content's width, but this addition would make things more foolproof.

See GIF of behavior: 
https://i.imgur.com/xTqPZQk.gif

**Comment by weotch** [comment]
Huh, surprised I hadn't run into that before.  Thanks!  The video was very useful.

**Comment by weotch** [comment]
Released as 2.0.5 now.
