### ISSUE TITLE
Look into issue where image with load:visible isn't appearing on load always

### ISSUE THREAD

**Issue by brokenhd** [BKWLD/vue-visual#6]
We suspect it's webpack dev server shenangins. Add a window on load listener perhaps ... and maybe a clunky timeout.

**Comment by weotch** [comment]
Test if `Document.readyState` is `loading`. If so, `addEventListener('DOMContentLoaded')` and update the inViewport settings.

See:
- http://www.w3schools.com/jsref/prop_doc_readystate.asp
- https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState
- https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

**Comment by weotch** [comment]
Here's what I did on Coachella for fitText, do something similar

```coffee
	mounted: ->
		@fitTagline()
		if document.readyState == 'loading'
			document.addEventListener 'readystatechange', handler = =>
				@fitTagline()
				if document.readyState == 'complete'
					document.removeEventListener 'readystatechange', handler

	# Setup fittext on the tagline
	methods: fitTagline: -> fitText @$refs.tagline, 4.2
```
